pollonium/pollonium/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

pollonium/polls/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views


app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^login/$', auth_views.LoginView.as_view(redirect_authenticated_user=True,
                                                  template_name='polls/login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page='polls:index',
                                                    template_name='polls/logout.html'), name='logout'),
    url(r'^(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.EditPollWizard.as_view(views.CREATE_FORMS), name='edit'),
    url(r'^create/$', views.CreatePollWizard.as_view(views.CREATE_FORMS), name='create'),
]

pollonium/polls/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from .models import Poll


class CreatePollGeneralForm(forms.ModelForm):
    """
    Form for creating a :model:`polls.Poll`. Let the user modify the general settings.
    """
    form_title = "What's the occasion?"

    class Meta:
        model = Poll
        fields = ('title', 'location', 'description')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': "What's the poll about"}),
            'location': forms.TextInput(attrs={'class': 'form-control', 'placeholder': "Where is happening"}),
            'description': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Tell the people more about this'}),
        }


class CreatePollChoicesForm(forms.Form):
    """
    Form for creating a :model:`polls.Poll`. Let the user add dynamically the choices.
    """
    form_title = 'What are the options?'

    def __init__(self, *args, **kwargs):
        super(CreatePollChoicesForm, self).__init__(*args, **kwargs)
        self.set_choice_fields(['', ])

    def set_choice_fields(self, choices):
        """
        Set the new form fields from a given list of :model:`polls.Choice` texts.

        :param choices: list of strings containing the :model:`polls.Choice` texts.
        """
        self.fields.clear()

        for i, c in zip(range(1, len(choices)+1), choices):
            self.fields['choice%s' % i] = forms.CharField(
                initial=c,
                required=True,
                label=i,
                widget=forms.TextInput(
                    attrs={'class': 'input form-control',
                   'placeholder': 'Option',
                   'id': 'choice%s' % i,
                   'name': 'choice%s'% i,
                   })
            )


class CreatePollSettingsForm(forms.ModelForm):
    """
    Form for creating a new :model:`polls.Poll`. Let the user modify the poll voting and sharing settings.
    """
    form_title = 'Configure your poll'

    class Meta:
        model = Poll
        fields = ('single_vote', 'limit_votes', 'votes_max', 'hidden_poll', 'only_invited')
        widgets = {
            'single_vote': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'limit_votes': forms.CheckboxInput(attrs={'class': 'form-check-input', 'id': 'limit_votes'}),
            'votes_max': forms.NumberInput(attrs={'class': 'form-control', 'id': 'votes_max'}),
            'hidden_poll': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'only_invited': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }


class SignUpForm(UserCreationForm):
    """
    Basic registration form for :model:`auth.User`.
    """
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)

pollonium/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.core.urlresolvers import reverse_lazy
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView

from formtools.wizard.views import SessionWizardView

from .models import Poll, Choice, Vote
from .forms import CreatePollGeneralForm, CreatePollChoicesForm, CreatePollSettingsForm, SignUpForm


class IndexView(ListView):
    """
    Display the polls index showing the ten latest :model:`polls.Poll` published.
    """
    template_name = 'polls/index.html'
    context_object_name = 'latest_polls'

    def get_queryset(self):
        """
        :return: query set with the ten latest no-hidden polls published
        """
        return Poll.objects.filter(pub_date__lte=timezone.now(), hidden_poll=False).order_by('-pub_date')[:10]


# TODO implement as class-based view
def detail(request, pk):
    """
    Display the partial results for a given :model:`polls.Poll`. Allow the user to vote for any of the options and
    display the current submitted votes.

    :param request: HTTP request
    :param pk: :model:`polls.Poll` instance primary-key
    :return: HTTP response
    """
    poll = get_object_or_404(Poll, pk=pk)
    if request.POST:
        try:
            # get the pk of the choice voted
            selected_choice = poll.choice_set.get(pk=request.POST['choice'])
        except (KeyError, Choice.DoesNotExist):
            # redisplay the view with error message
            messages.error(request, 'Ops! Error processing your vote. Please, try again!')
        else:
            # check for single vote
            if not poll.allowed_to_vote(request.user):
                messages.error(request, 'You only can vote once in this poll!')
            # check if the user has already vote this choice
            elif selected_choice.is_voted_by(request.user):
                messages.error(request, 'You cannot vote again this option. Please select another one and try again!')
            # check for poll vote limit per choice
            elif selected_choice.is_full():
                messages.error(request, 'The selected option cannot be voted anymore!')
            else:
                # submit the vote
                Vote.objects.create(poll=poll, choice=selected_choice, user=request.user)
                messages.success(request, 'Your vote has been submitted. Thanks for voting!')
            return HttpResponseRedirect(reverse('polls:detail', args=(poll.id,)))
        
    # populate table votes for each user {username: [choices_id,],}
    votes = poll.get_votes_list()
    vote_table = {}
    for user, choice_id in votes:
        vote_table.setdefault(user, []).append(choice_id)

    messages.get_messages(request).used = True
    return render(request, 'polls/details.html', {'poll': poll, 'vote_table': vote_table})


""" Forms used by each step of the :view:`polls.CreatePollWizard` """
CREATE_FORMS = [('general', CreatePollGeneralForm),
                ('choices', CreatePollChoicesForm),
                ('settings', CreatePollSettingsForm),
]

""" Templates used by each step of the :view:`polls.CreatePollWizard` """
CREATE_TEMPLATES = {i[0]: 'polls/create_%s.html' % i[0] for i in CREATE_FORMS}


class CreatePollWizard(LoginRequiredMixin, SessionWizardView):
    """
    Multi-step form view to create a :model:`polls.Poll`. Implements a server-side session. User must be logged-in to
    access this view.
    """
    login_url = 'polls:login'
    form_list = [CreatePollGeneralForm, CreatePollChoicesForm, CreatePollSettingsForm]

    def done(self, form_list, **kwargs):
        """
        Process form data after all steps are completed. Create a new :model:`polls.Poll` instance using the submitted
        data.

        :param form_list: form instances for each step
        :param kwargs: arbitrary keyword arguments
        :return: HTTP redirect to the created :model:`polls.Poll` detail view
        """
        if self.request.POST:
            poll = self.create_poll()
            return HttpResponseRedirect(reverse('polls:detail', args=(poll.id,)))

    def get_template_names(self):
        """
        :return: the template name for the current step
        """
        return [CREATE_TEMPLATES[self.steps.current]]

    def get_form(self, step=None, data=None, files=None):
        """
        Construct the form for a given step. If no step is defined, the current step will be determined automatically.
        The form will be initialized using the data argument to prefill the new form.


        :param step: step to process or None for current step
        :param data: data to initialize the form instance
        :param files: files to initialize the form instance
        :return: form instance for the given step
        """
        form = super(CreatePollWizard, self).get_form(step, data, files)

        if form.prefix == 'choices':
            # get the choices created at run-time in the client side
            choice_post = {k.strip('choices')[1:]:v
                           for (k, v) in self.get_form_step_data(form).items() if k.startswith('choices-choice')}
            # sort choices ascending and add them to the form instance
            choices = [choice_post[k] for k in sorted(choice_post)]
            form.set_choice_fields(choices or ['',])

        return form

    def get_form_fields(self):
        """
        :return: a 2-item tuple containing the form fields that correspond to the :model:`polls.Poll` model at first
        index, and :model:`polls.Choice` model at second index
        """
        # fields for poll model
        poll_model_f = self.get_cleaned_data_for_step('general') or {}
        poll_model_f.update(self.get_cleaned_data_for_step('settings') or {})

        # field for choice model
        choice_model_f = self.get_cleaned_data_for_step('choices') or {}
        choice_model_f = [choice_model_f[k] for k in sorted(choice_model_f)]

        return poll_model_f, choice_model_f

    def create_poll(self):
        """
        Create a :model:`polls.Poll` instance with the data submitted in all steps.

        :return: the created :model:`polls.Poll` instance
        """
        poll_f, choice_f = self.get_form_fields()

        # create and save the models
        poll = Poll.objects.create(
            title=poll_f['title'],
            location=poll_f['location'],
            description=poll_f['description'],
            author=self.request.user,
            single_vote=poll_f['single_vote'],
            limit_votes=poll_f['limit_votes'],
            votes_max=poll_f['votes_max'],
            hidden_poll=poll_f['hidden_poll'],
            only_invited=poll_f['only_invited'],
            pub_date=timezone.now(),
        )
        poll.save()

        for c in choice_f:
            Choice.objects.create(poll=poll, text=c)

        return poll


class EditPollWizard(CreatePollWizard):
    """
    Multi-step form view to edit the :model:`polls.Poll` content. Implements a server-side session. User must be
    logged-in to access this view.
    """
    def done(self, form_list, **kwargs):
        """
        Process form data after all steps are completed. Updates a :model:`polls.Poll` instance with the submitted data.

        :param form_list: form instances for each step
        :param kwargs: arbitrary keyword arguments
        :return: HTTP redirect to the created :model:`polls.Poll` detail view
        """
        if self.request.POST:
            poll = self.update_poll(self.kwargs['pk'])
            return HttpResponseRedirect(reverse('polls:detail', args=(poll.id,)))

    def get_form_initial(self, step):
        """
        Return a dictionary which will be passed as the initial argument when instantiating the form for the given
        step. Uses the :model:`polls.Poll` primary-key to get the poll instance.

        :param step: selected step
        :return: a dictionary containing the initialize data for the form of the given step
        """
        pk = self.kwargs['pk']
        if step == 'general' or step == 'settings':
            initial = Poll.objects.filter(pk=pk).values()[0]
        elif step == 'choices':
            ch = Poll.objects.get(pk=pk).choice_set.values()
            initial = {'choice%i' % i: ch[i-1]['text'] for i in range(1, len(ch)+1)}

        return self.initial_dict.get(step, initial or {})

    def update_poll(self, pk):
        """
        Update a :model:`polls.Poll` instance for the given primary-key, using the data submitted in all steps.
        The :model:`polls.Choice` set for the given :model:`polls.Poll` is cleared and then filled again with the new
        submitted options.

        :param pk: :model:`polls.Poll` primary-key
        :return: the updated :model:`polls.Poll` instance
        """
        poll_f, choice_f = self.get_form_fields()

        pq = Poll.objects.filter(pk=pk)
        pq.update(
            title=poll_f['title'],
            location=poll_f['location'],
            description=poll_f['description'],
            author=self.request.user,
            single_vote=poll_f['single_vote'],
            limit_votes=poll_f['limit_votes'],
            votes_max=poll_f['votes_max'],
            hidden_poll=poll_f['hidden_poll'],
            only_invited=poll_f['only_invited'],
            pub_date=timezone.now(),
        )

        # delete previous choice entries
        poll = pq.first()
        for c in poll.choice_set.iterator():
            c.delete()
        # add new choices
        for c in choice_f:
            Choice.objects.create(poll=poll, text=c)

        poll.save()
        return poll

    def get_form(self, step=None, data=None, files=None):
        """

pollonium/polls/templates/polls/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
    <head>
		<!-- Required meta tags -->
    	<meta charset="utf-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

		<!-- fonts -->
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
		<script src="https://www.w3schools.com/lib/w3.js"></script>

		<link rel="stylesheet" href="{% static 'polls/css/style.css' %}">
		<script src="{% static 'polls/js/actions.js' %}"></script>

		<title>pollonium: make a poll!</title>
		{% block head %}
		{% endblock %}
    </head>
	<body>
		<div class="page-header">
		   {% if user.is_authenticated %}
				<a href="{% url 'polls:create' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
				<a href="" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
				<p class="top-menu">Hello {{ user.username }} <small>(<a href="{% url 'polls:logout' %}">Log out</a>)</small></p>
			{% else %}
				<a href="{% url 'polls:login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
			{% endif %}
            <h1><a href="/polls">pollonium: make a poll!</a></h1>
		</div>
		<div class="container">
			<div class="row">
				<div class="col-md-1"></div>
				<div class="col-md-10 content rounded">
				{% block content %}
				{% endblock %}
				</div>
				<div class="col-md-1"></div>
			</div>
		</div>
	</body>
</html>

pollonium/polls/templates/polls/base_create.html
{% extends 'polls/base.html' %}

{% block head %}
{{ wizard.form.media }}
{% endblock %}

{% block content %}
<div class="text-center">
    <strong>STEP {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</strong>
    <h1>{{ form.form_title }}</h1>
</div>
<div class="content-panel rounded">
    <form role="form" data-toggle="validator" action="" method="post">
    {% csrf_token %}

        <div class="form-group row">
            <div class="col-md-3"></div>
            <div class="col-md-6" id="form-field">
                {% block form_content %}
                {% endblock %}
                <br><br>
                <div class="btn-group pull-right" role="group">
                    {% if wizard.steps.prev %}
                        <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}" class="btn"><span class="glyphicon glyphicon-chevron-left"></span></button>
                    {% endif %}
                    {% if editor_mode %}
                        <a class="btn btn-default" href="{% url 'polls:index'%}">Cancel</a>
                    {% endif %}
                    {% if wizard.steps.next %}
                        <button type="submit" value="submit" class="btn btn-success">Continue</button>
                    {% else %}
                        <button type="submit" value="submit" class="btn btn-success">Finish</button>
                    {% endif %}
                </div>
            </div>
            <div class="col-md-3"></div>
        </div>
    </form>
</div>
{% endblock %}

pollonium/polls/templates/polls/create_choices.html
{% extends 'polls/base_create.html' %}

{% block form_content %}

{{ wizard.management_form }}
{% for field in wizard.form %}
<div class="input-group group-choices" id="choice-row{{ forloop.counter }}">
    {{ field }}
    {% if forloop.last %}
    <span class="input-group-btn" id="btn-plus">
        <button class="btn btn-success add-input" type="button">
            <span class="glyphicon glyphicon-plus" />
        </button>
    </span>
    {% else %}
    <span class="input-group-btn">
        <button class="btn btn-danger remove-input" id="remove{{ forloop.counter }}" type="button">
            <span class="glyphicon glyphicon-minus" />
        </button>
    </span>
    {% endif %}
</div>
{% endfor %}
<input type="hidden" id="rowCount" value="{{ wizard.form.fields|length }}" />
{% endblock %}

pollonium/polls/templates/polls/create_general.html
{% extends 'polls/base_create.html' %}

{% block form_content %}
<table>
    {{ wizard.management_form }}
    {{ wizard.form }}
</table>
{% endblock %}

pollonium/polls/templates/polls/create_settings.html
{% extends 'polls/base_create.html' %}

{% block form_content %}
<table>
    {{ wizard.management_form }}
    {{ wizard.form }}
</table>
{% endblock %}

pollonium/polls/templates/polls/create_share.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

pollonium/polls/templates/polls/details.html
{% extends 'polls/base.html' %}

{% block content %}

{% with p=poll choices=poll.choice_set.all %}
<div class="text-center">
    <h1>{{ p.title }}</h1>
    <p>by <strong>{{ p.author }}</strong> · {{ p.pub_date|date:"M d, y" }}</p>
</div>
<div class="content-panel rounded">
    <p><span class="glyphicon glyphicon-map-marker detail-icon"></span>{{ p.location }}</p>
    <p><span class="glyphicon glyphicon-align-justify detail-icon"></span>{{ p.description }}</p>
    
    <form role="form" data-toggle="validator" action="{% url 'polls:detail' p.id %}" method="post">
    {% csrf_token %}
        <div class="form-check">
            
            <table class="table pagination-centered">
                <thead class="thead-inverse">
                    <tr>
                        <th></th>
                        {% for choice in choices %}
                            <th>{{ choice.text }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row"><font color="Green">Total</font></th>
                        {% for choice in choices %}
                            <th><font color="green">{{ choice.vote_count }}</font>
                            {% if p.limit_votes %}
                                / {{ p.votes_max }}
                            {% endif %}
                            </th>
                        {% endfor %}
                    </tr>
                    {% for username, u_choices in vote_table.items %}
                    <tr>
                        <th scope="row">{{ username }}</th> 
                        {% for choice in choices %}
                            <th>
                                {% if choice.id in u_choices %}
                                    <span class="glyphicon glyphicon-ok green" aria-hidden="true"></span>
                                {% endif %}
                            </th>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                    {% if not p.is_finished %}
                    <tr>
                        <th scope="row"></th>
                        {% for choice in choices %}
                            <td>
                                <input class="form-check-input" type="radio" name="choice" id="choice{{ forloop.counter }}"
                                    value="{{ choice.id }}"
                                    {% if choice.is_full %}
                                        disabled
                                    {% else %}
                                        required
                                    {% endif %}
                            /></td>
                        {% endfor %}
                    </tr>
                    {% endif %}
                </tbody>
            </table>

            {% if messages %}
                {% for message in messages %}
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    <div class="alert alert-danger" role="alert">
                        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                    <div class="alert alert-success" role="alert">
                        <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                {% endif %}
                    {{ message }}
                </div>
                {% endfor %}
            {% endif %}
            
            {% if p.is_finished %}
                <p class="pull-right"><strong>This poll is already closed!</strong></p>
            {% else %}
                <input type="submit" value="Vote" class="btn btn-success pull-right"/>
            {% endif %}

        </div>
    </form>
</div>
{% endwith %}

{% endblock %}

pollonium/polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block content %}
    <h2>What's people asking</h2>
    {% for poll in latest_polls %}
        <div class="list-group latest-polls">
            <a href="{% url 'polls:detail' poll.id %}" class="list-group-item">
            <h3 class="list-group-item-heading">{{ poll.title }}</h3>
            <p class="list-group-item-text">by {{ poll.author }} · {{ poll.pub_date|date:"M d, y" }}</p>
            </a>
        </div>
    {% empty %}
        <p>Seems nobody is asking anything ...</p>
    {% endfor %}
{% endblock %}

pollonium/polls/templates/polls/login.html
{% extends 'polls/base.html' %}
{% load i18n %}

{% block content %}
<div class="content-panel rounded">
    <form method="post" action=".">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{% trans 'Log in' %}" />
        <input type="hidden" name="next" value="{{ next }}" />
    </form>
    <p>{% trans "Not member" %}? <a href="{% url 'polls:signup' %}">{% trans "Register" %}</a>!</p>
</div>
{% endblock %}

pollonium/polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block content %}

<div class="content-panel rounded">
</div>
{% endblock %}

pollonium/polls/templates/polls/signup.html
{% extends 'polls/base.html' %}
{% load i18n %}

{% block content %}
<div class="content-panel rounded">
    {% if not request.user.is_authenticated %}
        <h2>{% trans "Sign up" %}</h2>
            <form method="post">
                {% csrf_token %}
                {% for field in form %}
                    <p>
                    {{ field.label_tag }}<br>
                    {{ field }}
                    {% if field.help_text %}
                        <small style="color: grey">{{ field.help_text }}</small>
                    {% endif %}
                    {% for error in field.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                    </p>
                {% endfor %}
            <button type="submit">{% trans "Sign up" %}</button>
        </form>
    {% else %}
        <p>{% trans "Please log out to sign up with a different account!" %}</p>
    {% endif %}
</div>
{% endblock %}